config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # chatroom test
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  # Defines the root path route ("/")
  # root "posts#index"
  resources :clubs do
    get '/cal', to: "clubs#cal"
    get '/events', to: "clubs#event"
    get 'invite/:invite_token', to: "club_members#new"
    resources :club_members, only: %i[index]
    resources :teams, only: %i[index new create]
    resources :locations, only: %i[index new create]
  end

  resources :teams, only: %i[show edit update destroy] do
    post '/coach', to: 'teams#coach'
    resources :events, only: %i[index new]
    resources :team_members, only: %i[index new create]
  end

  resources :club_members, only: %i[destroy edit update]
  resources :team_members, only: %i[destroy edit update]

  resources :events, only: %i[create destroy edit update show] do
    resources :attendances, only: %i[update]
    get "/chat", to: "events#chat"
  end

  resources :team_members, only: %i[destroy]
end

app/models/club.rb
class Club < ApplicationRecord
  has_secure_token :invite_token
  has_one_attached :photo
  has_many :teams, dependent: :destroy
  has_many :club_members, dependent: :destroy
  has_many :users, through: :club_members
  has_many :locations, dependent: :destroy
  geocoded_by :address
  validates :name, :description, :address, presence: true
  after_validation :geocode, if: :will_save_change_to_address?

  def member?(user)
    users.include?(user)
  end

  def make_cal(start_date)
    events = self.teams.flat_map { |team| team.events.where("start_time BETWEEN ? AND ?", start_date, start_date.next_day(6)) }

    monday = make_hour_arr(events.select { |event| event.start_time.to_date == start_date })
    tuesday = make_hour_arr(events.select { |event| event.start_time.to_date == start_date.next_day(1) })
    wednesday = make_hour_arr(events.select { |event| event.start_time.to_date == start_date.next_day(2) })
    thursday = make_hour_arr(events.select { |event| event.start_time.to_date == start_date.next_day(3) })
    friday = make_hour_arr(events.select { |event| event.start_time.to_date == start_date.next_day(4) })
    saturday = make_hour_arr(events.select { |event| event.start_time.to_date == start_date.next_day(5) })
    sunday = make_hour_arr(events.select { |event| event.start_time.to_date == start_date.next_day(6) })

    return [monday, tuesday, wednesday, thursday, friday, saturday, sunday]
  end

  private

  def make_hour_arr(arr)
    hour_slots = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
    arr.each do |event|
      case
      when event.start_time.hour < 8
        hour_slots[0] << event
      when event.start_time.hour == 8
        hour_slots[1] << event
      when event.start_time.hour == 9
        hour_slots[2] << event
      when event.start_time.hour == 10
        hour_slots[3] << event
      when event.start_time.hour == 11
        hour_slots[4] << event
      when event.start_time.hour == 12
        hour_slots[5] << event
      when event.start_time.hour == 13
        hour_slots[6] << event
      when event.start_time.hour == 14
        hour_slots[7] << event
      when event.start_time.hour == 15
        hour_slots[8] << event
      when event.start_time.hour == 16
        hour_slots[9] << event
      when event.start_time.hour == 17
        hour_slots[10] << event
      when event.start_time.hour == 18
        hour_slots[11] << event
      when event.start_time.hour == 19
        hour_slots[12] << event
      when event.start_time.hour == 20
        hour_slots[13] << event
      when event.start_time.hour == 21
        hour_slots[14] << event
      when event.start_time.hour >= 22
        hour_slots[15] << event
      end
    end
    return hour_slots
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: %i[show]

  def index
    @clubs = current_user.clubs.includes([:locations])
  end

  def show
    if @club.club_members.find_by(user_id: current_user.id).nil?
      redirect_to clubs_path
    end

    @upcoming_events = @club.teams.map { |team| team.events.where("end_time > ?", Time.now) }.flatten.sort_by { |event| event.start_time }
  end

  def new
    @club = Club.new
  end

  def create
    @club = Club.new(club_params)

    if @club.save
      @club_member = ClubMember.new
      @club_member.user = current_user
      @club_member.is_manager = true
      @club_member.club = @club
      if @club_member.save
        redirect_to club_path(@club)
      else
        @club.destroy
        render :new, status: :unprocessable_entity
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @club = Club.find(params[:id])
    redirect_to club_path(@club) unless current_user.manager?(@club)
  end

  def update
    @club = Club.find(params[:id])
    @club.update(club_params)

    if @club.save
      redirect_to club_path(@club)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @club = Club.find(params[:id])
    redirect_to club_path(@club) unless current_user.manager?(@club)
    @club.destroy
    redirect_to clubs_path, status: :see_other
  end

  def cal
    @club = Club.find(params[:club_id])

    unless current_user.club_members.find_by(club: @club).is_manager
      redirect_to club_path(@club)
    end

    if params[:start_date]
      @monday = Date.parse(params[:start_date]).beginning_of_week
    else
      @monday = Date.today.beginning_of_week
    end
    @cal = @club.make_cal(@monday)
  end

  def event
    @club = Club.find(params[:club_id])

    redirect_to club_path(@club) unless current_user.manager?(@club)

    @event = Event.new
  end

  private

  def club_params
    params.require(:club).permit(:name, :description, :address, :photo)
  end

  def set_club
    @club = Club.find(params[:id])
  end
end

app/views/clubs/_cal_row.html.erb
    <div class="cal-item">
      <h5 class="my-2"><%= start_time %> to <%= end_time %></h5>
    </div>
    <div class="cal-item" data-controller="popover" data-action="<%= @cal[0][time_slot].count == 0 ? "" : "mouseenter->popover#show mouseleave->popover#hide" %>">
      <p class="event-cell <%= "empty" if @cal[0][time_slot].count == 0 %> <%= @cal[0][time_slot].map { |event| event.team_member_id ? 0 : 1 }.sum > 0 ? "red-glow" : '' %>"><%= @cal[0][time_slot].count %></p>
      <% unless @cal[0][time_slot].count == 0 %>
        <%= render 'popcard', events: @cal[0][time_slot] %>
      <% end %>
    </div>
    <div class="cal-item" data-controller="popover" data-action="<%= @cal[1][time_slot].count == 0 ? "" : "mouseenter->popover#show mouseleave->popover#hide" %>">
      <p class="event-cell <%= "empty" if @cal[1][time_slot].count == 0 %> <%= @cal[1][time_slot].map { |event| event.team_member_id ? 0 : 1 }.sum > 0 ? "red-glow" : '' %>"><%= @cal[1][time_slot].count %></p>
      <% unless @cal[1][time_slot].count == 0 %>
        <%= render 'popcard', events: @cal[1][time_slot] %>
      <% end %>
    </div>
    <div class="cal-item" data-controller="popover" data-action="<%= @cal[2][time_slot].count == 0 ? "" : "mouseenter->popover#show mouseleave->popover#hide" %>">
      <p class="event-cell <%= "empty" if @cal[2][time_slot].count == 0 %> <%= @cal[2][time_slot].map { |event| event.team_member_id ? 0 : 1 }.sum > 0 ? "red-glow" : '' %>"><%= @cal[2][time_slot].count %></p>
      <% unless @cal[2][time_slot].count == 0 %>
        <%= render 'popcard', events: @cal[2][time_slot] %>
      <% end %>
    </div>
    <div class="cal-item" data-controller="popover" data-action="<%= @cal[3][time_slot].count == 0 ? "" : "mouseenter->popover#show mouseleave->popover#hide" %>">
      <p class="event-cell <%= "empty" if @cal[3][time_slot].count == 0 %> <%= @cal[3][time_slot].map { |event| event.team_member_id ? 0 : 1 }.sum > 0 ? "red-glow" : '' %>"><%= @cal[3][time_slot].count %></p>
      <% unless @cal[3][time_slot].count == 0 %>
        <%= render 'popcard', events: @cal[3][time_slot] %>
      <% end %>
    </div>
    <div class="cal-item" data-controller="popover" data-action="<%= @cal[4][time_slot].count == 0 ? "" : "mouseenter->popover#show mouseleave->popover#hide" %>">
      <p class="event-cell <%= "empty" if @cal[4][time_slot].count == 0 %> <%= @cal[4][time_slot].map { |event| event.team_member_id ? 0 : 1 }.sum > 0 ? "red-glow" : '' %>"><%= @cal[4][time_slot].count %></p>
      <% unless @cal[4][time_slot].count == 0 %>
        <%= render 'popcard', events: @cal[4][time_slot] %>
      <% end %>
    </div>
    <div class="cal-item" data-controller="popover" data-action="<%= @cal[5][time_slot].count == 0 ? "" : "mouseenter->popover#show mouseleave->popover#hide" %>">
      <p class="event-cell <%= "empty" if @cal[5][time_slot].count == 0 %> <%= @cal[5][time_slot].map { |event| event.team_member_id ? 0 : 1 }.sum > 0 ? "red-glow" : '' %>"><%= @cal[5][time_slot].count %></p>
      <% unless @cal[5][time_slot].count == 0 %>
        <%= render 'popcard', events: @cal[5][time_slot] %>
      <% end %>
    </div>
    <div class="cal-item" data-controller="popover" data-action="<%= @cal[6][time_slot].count == 0 ? "" : "mouseenter->popover#show mouseleave->popover#hide" %>">
      <p class="event-cell <%= "empty" if @cal[6][time_slot].count == 0 %> <%= @cal[6][time_slot].map { |event| event.team_member_id ? 0 : 1 }.sum > 0 ? "red-glow" : '' %>"><%= @cal[6][time_slot].count %></p>
      <% unless @cal[6][time_slot].count == 0 %>
        <%= render 'popcard', events: @cal[6][time_slot] %>
      <% end %>
    </div>

app/views/clubs/_event_form.html.erb
<div class="container">
  <div class="mx-auto" style="width: 30rem">
    <div class="text-center mt-5">
      <h2 class="text-white">New club event</h2>
    </div>

      <%= simple_form_for([club, event], method: :post, url: events_path) do |f| %>
        <%= f.input :title,
                    label: false,
                    input_html: { placeholder: "Title", class: "border-dark my-4 bg-info"} %>
        <%= f.input :description,
                    label: false,
                    input_html: { placeholder: "Description", class: "border-dark my-4 bg-info"} %>
        <%= f.association :team,
                    prompt: "Pick a team",
                    label: false,
                    input_html: {class: "border-dark my-4 bg-info"},
                    collection: club.teams %>
        <%= f.input :address,
                    label: false,
                    input_html: { placeholder: "Address", class: "border-dark my-4 bg-info"} %>
        <%= f.input :start_time,
                    as: :string,
                    label: false,
                    input_html: { data: { controller: "datepicker" }, placeholder: "Date", class: "border-dark my-4 bg-info" } %>
        <%= f.input :duration,
                    prompt: "Duration",
                    label:false,
                    collection: ['0:15', '0:30', '0:45', '1:00', '1:15', '1:30', '1:45', '2:00', '2:15', '2:30', '2:45', '3:00', '3:15', '3:30', '3:45', '4:00'],
                    input_html: { class: "border-dark my-4 bg-info"}  %>
        <div class="my-3form-actions text-center rounded d-grid gap-2">
          <%= f.submit "Submit Event", class:"btn btn-secondary bg-dark"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clubs/_form.html.erb
<%= simple_form_for(club) do |f| %>
  <%= f.input :name,
          label: false,
          input_html: { placeholder: "Name", class: "border-dark my-4 bg-info"}   %>
  <%= f.input :description,
          label: false,
          input_html: { placeholder: "Description", class: "border-dark my-4 bg-info"}   %>
  <%= f.input :photo, as: :file, label: false, input_html: { placeholder: "Pick a team", class: "border-dark my-4 bg-info"}  %>
  <%= f.input :address,
          label: false,
          input_html: {data: {address_autocomplete_target: "address"}, placeholder: "Address", class:"d-none"},
          wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
  <div class="my-3form-actions text-center rounded d-grid gap-2">
    <%= f.submit "Submit", class:"btn btn-secondary bg-dark"%>
  </div>

<% end %>

app/views/clubs/_popcard.html.erb
<template data-popover-target="content">
  <div data-popover-target="card" class="popcard">
    <% events.each do |event| %>
      <%= render "shared/event_card_team_name_small", event: event %>
    <% end %>
  </div>
</template>

app/views/clubs/cal.html.erb
<div class="container">
  <br>
  <div class="d-flex justify-content-between">
    <div class="">
      <form action="/clubs/<%= @club.id %>/cal" class="input-group">
        <input class="form-control flatpickr-input bg-info" data-controller="datepicker2" name="start_date" id="start_date" placeholder="Pick a date" value=<%= params[:start_date] || Date.today %> >
        <button type="submit" class="btn btn-dark">Go to Date</button>
      </form>
    </div>
    <%= link_to "New Event", club_events_path(@club), class: "btn btn-warning text-white"%>
  </div>
  <br>
  <div class="bg-info br p-3">
    <div class="d-flex justify-content-center align-items-center">
      <%= link_to club_cal_path(start_date: @monday.prev_day(7)), class: "text-black text-decoration-none me-3" do %>
        <h3 class='orange'><<</h3>
      <% end %>
      <h3>
        <%= @monday.strftime("%B %d, %Y") %> - <%= @monday.next_day(6).strftime("%B %d, %Y") %>
      </h3>
      <%= link_to club_cal_path(start_date: @monday.next_day(7)), class: "text-black text-decoration-none ms-3" do %>
        <h3 class='orange'>>></h3>
      <% end %>
    </div>
    <br>
    <div class="cal">
      <div class="cal-item">
        <h4>Start Time</h4>
      </div>
      <div class="cal-item">
        <h4><%= @monday.strftime("%a %d") %></h4>
      </div>
      <div class="cal-item">
        <h4><%= @monday.next_day(1).strftime("%a %d") %></h4>
      </div>
      <div class="cal-item">
        <h4><%= @monday.next_day(2).strftime("%a %d") %></h4>
      </div>
      <div class="cal-item">
        <h4><%= @monday.next_day(3).strftime("%a %d") %></h4>
      </div>
      <div class="cal-item">
        <h4><%= @monday.next_day(4).strftime("%a %d") %></h4>
      </div>
      <div class="cal-item">
        <h4><%= @monday.next_day(5).strftime("%a %d") %></h4>
      </div>
      <div class="cal-item">
        <h4><%= @monday.next_day(6).strftime("%a %d") %></h4>
      </div>
      <%= render 'cal_row', start_time: "00:00", end_time: "07:59", time_slot: 0 %>
      <%= render 'cal_row', start_time: "08:00", end_time: "08:59", time_slot: 1 %>
      <%= render 'cal_row', start_time: "09:00", end_time: "09:59", time_slot: 2 %>
      <%= render 'cal_row', start_time: "10:00", end_time: "10:59", time_slot: 3 %>
      <%= render 'cal_row', start_time: "11:00", end_time: "11:59", time_slot: 4 %>
      <%= render 'cal_row', start_time: "12:00", end_time: "12:59", time_slot: 5 %>
      <%= render 'cal_row', start_time: "13:00", end_time: "13:59", time_slot: 6 %>
      <%= render 'cal_row', start_time: "14:00", end_time: "14:59", time_slot: 7 %>
      <%= render 'cal_row', start_time: "15:00", end_time: "15:59", time_slot: 8 %>
      <%= render 'cal_row', start_time: "16:00", end_time: "16:59", time_slot: 9 %>
      <%= render 'cal_row', start_time: "17:00", end_time: "17:59", time_slot: 10 %>
      <%= render 'cal_row', start_time: "18:00", end_time: "18:59", time_slot: 11 %>
      <%= render 'cal_row', start_time: "19:00", end_time: "19:59", time_slot: 12 %>
      <%= render 'cal_row', start_time: "20:00", end_time: "20:59", time_slot: 13 %>
      <%= render 'cal_row', start_time: "21:00", end_time: "21:59", time_slot: 14 %>
      <%= render 'cal_row', start_time: "22:00", end_time: "23:59", time_slot: 15 %>

    </div>
  </div>
  <br>
</div>

app/views/clubs/edit.html.erb
<div class="container">
  <div class="mx-auto" style="width: 30rem">
    <div class="text-center mt-5">
      <h2>Edit club</h2>
    </div>
        <%= render 'form', club: @club %>
    </div>
  </div>
</div>

app/views/clubs/event.html.erb
<%= render "event_form", club: @club, event: @event %>

app/views/clubs/index.html.erb
<div class="container">
  <br>
  <div class="d-flex justify-content-end">
    <%= link_to 'New club', new_club_path, class: 'btn btn-warning text-white' %>
  </div>
  <% if @clubs.length == 0 %>
    <h4>You have not joined any clubs yet</h4>
  <% else %>
    <div class="row">
      <% @clubs.each do |club| %>
        <div class="col-lg-6 col-12">
          <%= render "shared/club_card", club: club %>
        </div>
      <% end %>
    </div>
  <% end %>
  <br>
</div>

app/views/clubs/new.html.erb
<div class="container">
  <div class="mx-auto" style="width: 30rem">
    <div class="text-center mt-5">
      <h2>New club</h2>
    </div>

    <%= render 'form', club: @club %>
    </div>
  </div>
</div>

app/views/clubs/show.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-lg-4 col-12">
      <div>
        <h2 class='mt-2 text-white'>Club Page</h2>
        <%= render 'shared/club_card_big', club: @club %>
        <p class="my-5"><%= render 'shared/invite_link', club: @club %></p>
      </div>
      <div class="mt-5">
          <h2 class='text-white d-flex justify-content-between'>Teams <%= link_to 'Create team', new_club_team_path(@club), class:'btn btn-warning text-white br' %></h2>
          <% if @club.teams.length == 0 %>
            <h5 class="mt-3 text-white">This club does not have any teams yet</h5>
          <% else %>
            <% @club.teams.each do |team| %>
              <%= render 'shared/team_card', team: team %>
            <% end %>
          <% end %>
      </div>
    </div>



    <div class="col-lg-8 col-12">
      <div>
        <h2 class='mt-2 text-white'>Upcoming Events</h2>
        <% if @upcoming_events.length == 0 %>
          <h4>No upcoming events</h4>
        <% else %>
          <% @upcoming_events.each do |event| %>
            <%= render 'shared/event_card', event: event %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <br>
</div>