config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # chatroom test
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  # Defines the root path route ("/")
  # root "posts#index"
  resources :clubs do
    get '/cal', to: "clubs#cal"
    get '/events', to: "clubs#event"
    get 'invite/:invite_token', to: "club_members#new"
    resources :club_members, only: %i[index]
    resources :teams, only: %i[index new create]
    resources :locations, only: %i[index new create]
  end

  resources :teams, only: %i[show edit update destroy] do
    post '/coach', to: 'teams#coach'
    resources :events, only: %i[index new]
    resources :team_members, only: %i[index new create]
  end

  resources :club_members, only: %i[destroy edit update]
  resources :team_members, only: %i[destroy edit update]

  resources :events, only: %i[create destroy edit update show] do
    resources :attendances, only: %i[update]
    get "/chat", to: "events#chat"
  end

  resources :team_members, only: %i[destroy]
end

app/views/shared/_back.html.erb
<div class="btn-back pt-2">
  <a href="#" class="inherit-all mx-3" onclick="history.back()"><i class="fa-solid fa-arrow-left"></i></a>
</div>

app/views/shared/_club_card_big.html.erb
<%= link_to club_path(club), class: "inherit-all" do %>
  <div class="team-card br box-shadow position-relative">
    <div class="d-flex flex-column">
      <% if club.photo.key %>
        <div class="d-flex flex-column justify-content-center h-100 mx-auto">
          <div>
            <%= cl_image_tag club.photo.key, alt: "#{club.name} logo", class: 'img-fill' %>
          </div>
          <br>
        </div>
      <% end %>
      <div class="something">
        <h2><%= club.name %></h2>
        <h5><%= club.address %></h5>
        <h6>Club Locations: <%= club.locations.count %></h6>
        <p><%= club.description %></p>
        <% if user = ClubMember.find_by(user: current_user, club: club).is_manager %>
        <div class='buttons'>
          <%= link_to edit_club_path(club), class: 'btn btn-primary br' do %>
            <i class="fa-regular fa-pen-to-square"></i>
          <% end %>
          <%= link_to club_cal_path(club), class: 'btn btn-warning br text-white' do %>
            <i class="fa-regular fa-calendar-days"></i>
          <% end %>
          <%= link_to club_path(club), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-danger br text-white' do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_event_card.html.erb
<%= link_to event_path(event), class:'inherit-all' do %>
  <div class="event-card br box-shadow mt-3">
    <div class="d-flex justify-content-between align-items-center">
      <div class="d-flex align-items-center">
        <div class='text-center mx-4'>
          <p class='m-0'><%= event.start_time.strftime('%b') %></p>
          <p class='h1 m-0 orange'><%= event.start_time.strftime('%d') %></p>
          <p class='m-0'><%= event.start_time.strftime('%a') %></p>
        </div>
        <div class='mx-3'>
          <h3><strong><%= event.title %></strong></h3>
          <% if event.location_id  %>
            <small> <strong>@<%= (Location.find(event.location_id)).name %></strong></small>
          <% end %>
          <p class="mb-0"><%= event.description %></p>
           <p class="mb-1"><%= event.team.name %></p>
        </div>
    </div>
      <div class='mx-5 '>
        <p class='my-0'><%= event.start_time.strftime('%H:%M') %></p>
        <p class='text-center my-0'>-</p>
        <p class='my-0'><%= event.end_time.strftime('%H:%M') %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_event_card_team_name_small.html.erb
<%= link_to event_path(event), class:'inherit-all' do %>
  <div class="event-card br shadow <%= "red-glow" unless event.team_member_id %>" style="min-width: 250px">
    <div class="d-flex justify-content-between align-items-center">
      <div class="d-flex align-items-center">
        <div class='mx-3'>
          <h6><strong><%= event.title %></strong></h6>
          <% if event.location_id %>
            <small> <strong>@<%= (Location.find(event.location_id)).name %></strong></small>
          <% end %>
          <p><%= event.description %></p>
          <%= event.team.name %>
        </div>
    </div>
      <div class='mx-3'>
        <p class='my-0'><%= event.start_time.strftime('%H:%M') %></p>
        <p class='text-center my-0'>-</p>
        <p class='my-0'><%= event.end_time.strftime('%H:%M') %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_event_card_teamname.html.erb
<%= link_to event_path(event), class:'inherit-all' do %>
  <div class="event-card br box-shadow">
    <div class="d-flex justify-content-between align-items-center">
      <div class="d-flex align-items-center">
        <div class='text-center mx-3'>
          <p class='m-0'><%= event.start_time.strftime('%b') %></p>
          <p class='h1 m-0 orange'><%= event.start_time.strftime('%d') %></p>
          <p class='m-0'><%= event.start_time.strftime('%a') %></p>
        </div>
        <div class='mx-3 '>
        <div class='d-flex align-items-baseline'>
          <h3><strong><%= event.title %>  </strong></h3>
        </div>
          <em> <%= event.address %></em>
          <% if event.location_id %>
            <small> <strong>@<%= (Location.find(event.location_id)).name %></strong></small>
          <% end %>
          <p><%= event.description %></p>
          <p><%= event.team.club.name %> - <%= event.team.name %></p>
        </div>
    </div>
      <div class='mx-3'>
        <p class='my-0'><%= event.start_time.strftime('%H:%M') %></p>
        <p class='text-center my-0'>-</p>
        <p class='my-0'><%= event.end_time.strftime('%H:%M') %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_invite_link.html.erb
<h2 class='text-white'>Invite Link</h2>
<div data-controller="clipboard" data-clipboard-success-content-value="Copied!" class="input-group my-3 shadow-sm">
  <input type="text" value="<%= "https://www.go-turbo.me/clubs/#{club.id}/invite/#{club.invite_token}" %>" data-clipboard-target="source"  class="form-control bg-white"/>
  <button type="button" data-action="clipboard#copy" data-clipboard-target="button" class="btn btn-dark">Copy to clipboard</button>
</div>

app/views/shared/_location_card.html.erb
<%= link_to club_locations_path(location), class:'inherit-all' do %>
  <div class="location-card br box-shadow bg-info p-2 ">
    <h2><%= location.name %></h2>
    <h4><%= location.club.name %></h4>
    <p><%= location.description %></p>
    <% if current_user.manager?(location) %>
      <div class='buttons'>
        <%= link_to edit_location_path(location), class: 'btn btn-primary br' do %>
          <i class="fa-regular fa-pen-to-square"></i>
        <% end %>
        <%= link_to location_path(location), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-danger br text-white' do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark bg-dark navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "TURBO.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto text-light">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar text-decoration-none" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <h3 class="text-light m-0"><%= current_user.fullname %></h3>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My clubs", clubs_path, class: "dropdown-item border-bottom" %>
              <%= link_to "My teams", club_teams_path(current_user.teams), class: "dropdown-item border-bottom" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item border-bottom" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_players_list.html.erb
<% user = User.find(team_member.user_id) %>
<div class="d-flex justify-content-between align-items-center bg-white border-bottom">
  <p class='list-group-item bg-white m-0 border-0'><%= user.fullname %></p>
  <div>
    <% if team_member.is_coach %>
      <i class="fa-solid fa-user-tie orange mx-2"></i>
    <% end %>
    <% if team_member.attendances.find_by(event: Event.find(params[:id]))&.absence  %>
      <i class="fa-solid fa-circle-xmark mx-3 text-danger"></i>
    <% else %>
      <i class="fa-solid fa-check mx-3 text-success"></i>
    <% end %>
  </div>
</div>

app/views/shared/_players_list_comment.html.erb
<% user = User.find(team_member.user_id) %>
<div class="bg-white border-bottom">
  <div class="d-flex justify-content-between align-items-center ">
    <p class='list-group-item bg-white m-0 border-0'><%= user.fullname %></p>
    <div>
      <% if team_member.is_coach %>
        <i class="fa-solid fa-user-tie orange mx-2"></i>
      <% end %>
      <% if team_member.attendances.find_by(event: Event.find(params[:id])).absence  %>
        <i class="fa-solid fa-circle-xmark mx-3 text-danger"></i>
      <% else %>
        <i class="fa-solid fa-check mx-3 text-success"></i>
      <% end %>
    </div>
  </div>
  <p class='list-group-item bg-white m-0 border-0 text-wrap text-break'><%= team_member.attendances.find_by(event: Event.find(params[:id])).comment %></p>
</div>

app/views/shared/_players_list_team.html.erb
<% user = User.find(team_member.user_id) %>
<div class="d-flex justify-content-between align-items-center bg-white border-bottom">
  <p class='list-group-item bg-white m-0 border-0'><%= user.fullname %></p>
  <div>
    <% if team_member.is_coach %>
        <i class="fa-solid fa-user-tie orange mx-2"></i>
      <% end %>
    <% if current_user.coach_or_manager?(team) %>
      <%= link_to team_member_path(team_member), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:'bg-white' do %>
        <i class="fa-solid fa-xmark text-black mx-3"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_team_card.html.erb
<%= link_to team_path(team), class:'inherit-all' do %>
  <div class="team-card br box-shadow">
    <div class="d-flex">
      <% if team.club.photo.key %>
        <div class="me-3 d-flex flex-column justify-content-center h-100 my-auto">
          <div style="max-width: 50px" >
            <%= cl_image_tag team.club.photo.key, alt: "#{team.club.name} logo", class: 'img-fill' %>
          </div>
        </div>
      <% end %>
      <div class="something">
        <h2><%= team.name %></h2>
        <% if team.valid_sport? %>
          <p><strong><%= team.sport.capitalize %></strong> <%= image_tag team.get_icon, class: "iconize" %></p>
        <% else %>
          <p><strong><%= team.sport.capitalize %></strong></p>
        <% end %>
        <h4><%= team.club.name %></h4>
        <p><%= team.description %></p>
        <p><em><%= team.team_members.size %> members</em></p>
        <% if current_user.coach_or_manager?(team) %>
          <div class='buttons'>
            <%= link_to edit_team_path(team), class: 'btn btn-primary br' do %>
              <i class="fa-regular fa-pen-to-square"></i>
            <% end %>
            <%= link_to team_path(team), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-danger br text-white' do %>
              <i class="fa-solid fa-trash"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_team_card_show.html.erb
  <div class="team-card-show br box-shadow mt-4 pb-3">
    <div class="d-flex">
      <% if team.club.photo.key %>
        <div class="me-3 d-flex flex-column justify-content-center h-100 my-auto">
          <div style="max-width: 50px" >
            <%= cl_image_tag team.club.photo.key, alt: "#{team.club.name} logo", class: 'img-fill' %>
          </div>
        </div>
      <% end %>
      <div class="something">
        <h2><%= team.name %></h2>
        <% if team.valid_sport? %>
          <p><strong><%= team.sport.capitalize %></strong> <%= image_tag team.get_icon, class: "iconize" %></p>
        <% else %>
          <p><strong><%= team.sport.capitalize %></strong></p>
        <% end %>
        <h4><%= team.club.name %></h4>
        <p><%= team.description %></p>
        <p><em><%= team.team_members.count %> members</em></p>
        <% if current_user.coach_or_manager?(team) %>
          <div class='buttons'>
            <%= link_to edit_team_path(team), class: 'btn btn-primary br' do %>
              <i class="fa-regular fa-pen-to-square"></i>
            <% end %>
            <%= link_to team_path(team), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-danger br text-white' do %>
              <i class="fa-solid fa-trash"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>