config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # chatroom test
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  # Defines the root path route ("/")
  # root "posts#index"
  resources :clubs do
    get '/cal', to: "clubs#cal"
    get '/events', to: "clubs#event"
    get 'invite/:invite_token', to: "club_members#new"
    resources :club_members, only: %i[index]
    resources :teams, only: %i[index new create]
    resources :locations, only: %i[index new create]
  end

  resources :teams, only: %i[show edit update destroy] do
    post '/coach', to: 'teams#coach'
    resources :events, only: %i[index new]
    resources :team_members, only: %i[index new create]
  end

  resources :club_members, only: %i[destroy edit update]
  resources :team_members, only: %i[destroy edit update]

  resources :events, only: %i[create destroy edit update show] do
    resources :attendances, only: %i[update]
    get "/chat", to: "events#chat"
  end

  resources :team_members, only: %i[destroy]
end

app/models/event.rb
class Event < ApplicationRecord
  attr_accessor :duration

  belongs_to :team
  has_many :attendances, dependent: :destroy
  geocoded_by :address
  validates :start_time, :end_time, :description, :title, presence: true
  after_validation :geocode, if: :will_save_change_to_address?

  def team_member
    TeamMember.find(self.team_member_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_team, only: %i[new]
  def index
    @events = current_user.teams.map {|team| team.events}.flatten
  end

  def show
    @event = Event.find(params[:id])
    @attendance = Attendance.find_by(event: @event, team_member: TeamMember.find_by(user: current_user, team: @event.team))

    @absent_team_members = @event.team.team_members.includes([:user]).select{|team_member| team_member.attendances.find_by(event: @event).absence == true if team_member.attendances.find_by(event: @event) }
    @present_team_members = @event.team.team_members - @absent_team_members
    @present_team_members = @present_team_members.sort_by { |member | member.user.fullname}
    @absent_team_members = @absent_team_members.sort_by { |member | member.user.fullname}

    if @event.address && @event.address != ""
      @marker =
        {
          lat: @event.latitude,
          lng: @event.longitude
        }
    else
      @marker =
        {
          lat: @event.team.club.latitude,
          lng: @event.team.club.longitude
        }
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    hours = @event.duration[0].to_i
    minutes = @event.duration[2..3].to_i
    @event.end_time = @event.start_time + (minutes * 60) + (hours * 60 * 60)

    if @event.save!
      @event.team.team_members.each {|member| Attendance.create!(event: @event, team_member: member)}
      redirect_to team_path(@event.team)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
    @team = @event.team
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    @team = @event.team
    if @event.save!
      flash[:notice] = "Event updated"
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @team = @event.team
    @event.destroy
    redirect_to team_path(@team), status: :see_other
  end

  def chat
    @event = Event.find(params[:event_id])
    if @event.chatroom_id
      redirect_to chatroom_path(@event.chatroom_id)
    else
      Chatroom.find_by(name: @event.title) ? @chatroom = Chatroom.find_by(name: @event.title) : @chatroom = Chatroom.create(name: @event.title)
      @event.chatroom_id = @chatroom.id
      redirect_to chatroom_path(@event.chatroom_id)
    end
  end

  private

  def set_team
    @team = Team.find(params[:team_id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :start_time, :team_id, :duration, :address, :team_member_id)
  end
end

app/views/events/_card.html.erb
<div class="container">
  <div class="event-card">
    <div class="d-flex justify-content-between w-auto">
      <div class="event-time">
        <%= event.start_time %>
        <%= event.end_time %>
      </div>
      <div class="event-title">
        <%= event.title %>
        <%= event.description %>
        <%= event.address %>
      </div>
      <%# <div class="event-location">
        <%= event.location %>
      <%# </div> %>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class="container">
  <div class="mx-auto" style="width: 30rem">
    <div class="text-center mt-5">
      <h2 class="text-white">New event</h2>
    </div>
      <%= simple_form_for([team, event], method: :post, url: events_path) do |f| %>
        <%= f.input :title,
                    label: false,
                    input_html: { placeholder: "Title", class: "border-dark my-4 bg-info"}  %>
        <%= f.input :description,
                    label: false,
                    input_html: { placeholder: "Description", class: "border-dark my-4 bg-info"} %>
        <%= f.input :team_id,
                    label: false,
                    input_html: { placeholder: "Team", class: "border-dark my-4 bg-info"}, as: :hidden, input_html: { value: team.id } %>
        <%= f.input :team_member_id, label: false, prompt: "Coach Responsible", collection: team.team_members.where( is_coach: true ), label_method: :member_name, value_method: :id, input_html: {class: "border-dark my-4 bg-info"}  %>
        <%= f.input :address,
                    label: false,
                    input_html: {data: {address_autocomplete_target: "address"}, placeholder: "Address", class:"d-none"},
                    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
        <%= f.input :start_time,
                    as: :string,
                    label: false,
                    input_html: { data: { controller: "datepicker" }, placeholder: "Date", class: "border-dark my-4 bg-info" } %>
        <%= f.input :duration,
                    prompt: "Duration",
                    label:false,
                    collection: ['0:15', '0:30', '0:45', '1:00', '1:15', '1:30', '1:45', '2:00', '2:15', '2:30', '2:45', '3:00', '3:15', '3:30', '3:45', '4:00'],
                    input_html: { class: "border-dark my-4 bg-info"}  %>
        <div class="my-3form-actions text-center rounded d-grid gap-2">
          <%= f.submit "Submit Event", class:"btn btn-secondary bg-dark"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <div class="mx-auto" style="width: 30rem">
    <div class="text-center mt-5">
      <h2  class="text-white">Edit this event</h2>
    </div>

      <%= simple_form_for @event do |f| %>
                <%= f.input :title,
                    label: false,
                    input_html: { placeholder: "Title", class: "border-dark my-4 bg-info"}  %>
        <%= f.input :description,
                    label: false,
                    input_html: { placeholder: "Description", class: "border-dark my-4 bg-info"} %>
        <%= f.input :team_id,
                    label: false,
                    input_html: { placeholder: "Team", class: "border-dark my-4 bg-info"}, as: :hidden, input_html: { value: @event.team.id } %>
        <%= f.input :team_member_id, label: false, prompt: "Coach Responsible", collection: @event.team.team_members.where( is_coach: true ), label_method: :member_name, value_method: :id, input_html: {class: "border-dark my-4 bg-info"}  %>
        <%= f.input :address,
                    label: false,
                    input_html: {data: {address_autocomplete_target: "address"}, placeholder: "Address", class:"d-none"},
                    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
        <%= f.input :start_time,
                    as: :string,
                    label: false,
                    input_html: { data: { controller: "datepicker" }, placeholder: "Date", class: "border-dark my-4 bg-info" } %>
        <%= f.input :duration,
                    prompt: "Duration",
                    label:false,
                    collection: ['0:15', '0:30', '0:45', '1:00', '1:15', '1:30', '1:45', '2:00', '2:15', '2:30', '2:45', '3:00', '3:15', '3:30', '3:45', '4:00'],
                    input_html: { class: "border-dark my-4 bg-info"}  %>
        <div class="my-3form-actions text-center rounded d-grid gap-2">
          <%= f.submit "Submit Event", class:"btn btn-secondary bg-dark"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<h1>Events</h1>
<% @events.each do |event| %>
    <%= link_to event_path(event) do %>
    <%= render "card" , event: event%>
  <% end %>
<% end %>
<%= link_to 'Create Event', new_team_event_path %>

app/views/events/new.html.erb
<%= render "form", event: @event, team: @team%>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-7 col-12">
      <div class="fixed-on-scroll">
        <div class="team-card-show box-shadow br px-4">
          <h2><%= @event.title %></h2>
          <p><%= @event.description %></p>
          <p><%= @event.start_time.strftime('%H:%M') %> - <%= @event.end_time.strftime('%H:%M') %></p>
          <% if @event.team_member_id %>
            <p><strong>Coach: </strong><%= @event.team_member.user.fullname%></p>
          <% else %>
            <p><strong>Coach: </strong>No coach assigned to this event yet</p>
          <% end %>
          <% if current_user.coach_or_manager?(@event.team) %>
            <div class='buttons'>
              <%= link_to edit_event_path(@event), class: 'btn btn-primary br' do %>
                <i class="fa-regular fa-pen-to-square"></i>
              <% end %>
              <%= link_to event_path(@event), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-danger br text-white' do %>
                <i class="fa-solid fa-trash"></i>
              <% end %>
            </div>
          <% end %>
          <%  %>
        </div>
        <div class="event-card br box-shadow p-3">
          <div class='br' style="width: 95%; height: 50vh; margin: 10px auto;"
            data-controller="map"
            data-map-marker-value="<%= @marker.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
      </div>
      </div>
    <div class="col-lg-5 col-12">
      <div class="my-20">
        <%= link_to "Chat", event_chat_path(@event), class: "btn btn-dark w-100 br" %>
      </div>
      <% if @attendance %>
        <div class="event-card box-shadow br p-3 text-center">
          <h3>Will you be there?</h3>
          <%= simple_form_for [@event, @attendance], html: {novalidate: true, class: "no-validation"} do |f| %>
            <div class="toggle-radio m-3">
              <input type="radio" name="rdo" id="yes" value="yes" <%= "checked" unless  @attendance.absence%> >
              <input type="radio" name="rdo" id="no" value="no" <%= "checked" if  @attendance.absence%>>
              <div class="switch">
                <label for="yes">Yes</label>
                <label for="no">No</label>
                <span></span>
              </div>
            </div>
            <%= f.input :comment, label: false, required: false, input_html: { placeholder: "Tell the coach why", class: "bg-info" } %>
            <%= f.button :submit, "Save Attendance", class: "btn btn-primary br" %>
          <% end %>
        </div>
      <% end %>
      <h4 class='my-3 text-white'>Present players</h4>
      <div class='players-list-card p-2 br box-shadow bg-white mb-5 list-group'>
          <% @present_team_members.each do |team_member| %>
            <%= render 'shared/players_list', team_member: team_member, team: @event.team %>
          <% end %>
      </div>
      <% if @absent_team_members.length != 0 %>
        <h4 class='text-white'>Absent players</h4>
          <div class='players-list-card p-1 br box-shadow bg-white mb-1 list-group'>
              <% @absent_team_members.each do |team_member| %>
                <% if current_user.coach_or_manager?(@event.team) %>
                  <%= render 'shared/players_list_comment', team_member: team_member, team: @event.team %>
                <% else %>
                  <%= render 'shared/players_list', team_member: team_member, team: @event.team %>
                <% end %>
              <% end %>
          </div>
        <% end %>
      <br>
    </div>
  </div>
  <br>
</div>