config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # chatroom test
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  # Defines the root path route ("/")
  # root "posts#index"
  resources :clubs do
    get '/cal', to: "clubs#cal"
    get '/events', to: "clubs#event"
    get 'invite/:invite_token', to: "club_members#new"
    resources :club_members, only: %i[index]
    resources :teams, only: %i[index new create]
    resources :locations, only: %i[index new create]
  end

  resources :teams, only: %i[show edit update destroy] do
    post '/coach', to: 'teams#coach'
    resources :events, only: %i[index new]
    resources :team_members, only: %i[index new create]
  end

  resources :club_members, only: %i[destroy edit update]
  resources :team_members, only: %i[destroy edit update]

  resources :events, only: %i[create destroy edit update show] do
    resources :attendances, only: %i[update]
    get "/chat", to: "events#chat"
  end

  resources :team_members, only: %i[destroy]
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :club, counter_cache: true
  has_many :events

  validates :name, :description, presence: true
  validates :name, uniqueness: true
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_club, only: [:new, :create]
  def index
    @locations = Location.all
  end

  def new
    redirect_to club_path(@club) unless current_user.manager?(@club)
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.club = @club
    if @location.save
      redirect_to club_locations_path(@location)
    else
      render new, status: :unprocessable_entity
    end
  end

  private

  def set_club
    @club = Club.find(params[:club_id])
  end

  def location_params
    params.require(:location).permit(:name, :description, :address)
  end
end

app/views/locations/edit.html.erb
<div class="container">
  <div class="mx-auto" style="width: 30rem">
    <div class="text-center mt-5">
      <h2>Edit location</h2>
    </div>

      <%= simple_form_for [@club, @location] do |f| %>
        <%= f.input :name,
                    label: false,
                    input_html: { placeholder: "Name", class: "border-dark my-4 bg-info"}  %>
        <%= f.input :description,
                    label: false,
                    input_html: { placeholder: "Description", class: "border-dark my-4 bg-info"}  %>
        <%= f.input :address,
                    label: false,
                    input_html: { placeholder: "Address", class: "border-dark my-4 bg-info"}  %>
         <div class="my-3form-actions text-center rounded d-grid gap-2">
          <%= f.submit "Submit Edited Location", class:"btn btn-secondary bg-dark"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/locations/index.html.erb
<div class="container">
  <div class="row justify-content-center ">
    <div class="mt-4 ml-5">
      <h1>My locations</h1> <%= link_to 'Create location', new_club_location_path, class: "btn btn-primary br" %>
    </div>
      <div class="d-flex flex-column w-75">
      <% if @locations.length == 0 %>
        <h4>You have no locations yet</h4>
      <% else %>
          <% @locations.each do | location | %>
            <div class="m-3">
              <%= render 'shared/location_card', location: location %>
            </div>
          <% end %>
        <% end %>
      </div>
  </div>
</div>

app/views/locations/new.html.erb
<div class="container">
  <div class="mx-auto" style="width: 30rem">
    <div class="text-center mt-5">
      <h2>Create new location</h2>
    </div>

      <%= simple_form_for [@club, @location] do |f| %>
        <%= f.input :name,
                    label: false,
                    input_html: { placeholder: "Name", class: "border-dark my-4 bg-info"}  %>
        <%= f.input :description,
                    label: false,
                    input_html: { placeholder: "Description", class: "border-dark my-4 bg-info"}  %>
        <%= f.input :address,
                    label: false,
                    input_html: { placeholder: "Address", class: "border-dark my-4 bg-info"}  %>
         <div class="my-3form-actions text-center rounded d-grid gap-2">
          <%= f.submit "Submit Location", class:"btn btn-secondary bg-dark"%>
        </div>
      <% end %>
    </div>
  </div>
</div>